### ISSUE TITLE
Add end-to-end tests

### ISSUE THREAD

**Issue by karllhughes** [thegraidenetwork/rubric-creator#24]
## What we're doing
Adding more end-to-end tests to the suite.

## Why we're doing it
These tests help prevent regression and ensure that our core functionality is working before pushing updates.

## How it should be done
Tests we still need:

- Online user can create a duplicated rubric
- Online user can remove a private rubric from their list
- Online user can create a rubric on mobile
- Offline user is shown message when trying to create a rubric

There are probably more we could add. Existing [end to end tests can be found in this file](https://github.com/thegraidenetwork/rubric-creator/blob/master/e2e/app.e2e-spec.ts).

**Comment by ANickow** [comment]
Created #75 - separating out e2e tests for online functionality into a unique issue
