### ISSUE TITLE
Update footer copyright date to use a dynamic year

### ISSUE THREAD

**Issue by karllhughes** [thegraidenetwork/rubric-creator#63]
## What?
We should use a dynamic component to insert the current year in the footer rather than the hard-coded `2018` we're using now.

## Why?
Once done, we'll never have to come back to change the date in Rubric Creator's footer. 🙌

## How?
`getYear` will probably work: https://www.tutorialspoint.com/javascript/date_getyear.htm

**Comment by ANickow** [comment]
@karllhughes - The README also has a copyright year in it - We can't use the same solution to dynamically update that date in a markdown file. . . . Thoughts?

**Comment by karllhughes** [comment]
I think we'll just have to do it manually in the README then. I don't know of any creative solutions that will get around that.

**Comment by ANickow** [comment]
Yeah I tried looking for some options to add dynamic values to markdown files and it doesn't seem worth it.  I will update the README and the LICENSE files in this PR (found another reference there)
